//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nesne_Prog_Proje.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTasarimRehberimEntities : DbContext
    {
        public DbTasarimRehberimEntities()
            : base("name=DbTasarimRehberimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCizim> TblCizim { get; set; }
        public virtual DbSet<TblMalzemeler> TblMalzemeler { get; set; }
        public virtual DbSet<TblMetraj> TblMetraj { get; set; }
        public virtual DbSet<TblPlanlarim> TblPlanlarim { get; set; }
    }
}
