//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nesne_Prog_Proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMetraj
    {
        public int ID { get; set; }
        public string Aciklama { get; set; }
        public string MetrajMalzeme { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> ToplamKg { get; set; }
    }
}
